EDSC-1181 Handle errors fromm CMR when generating download script.

diff --git a/app/views/granules/prepare_script.html.erb b/app/views/granules/prepare_script.html.erb
--- a/app/views/granules/prepare_script.html.erb
+++ b/app/views/granules/prepare_script.html.erb
@@ -54,13 +54,13 @@ netrc=$(mktemp netrc.XXXXXXXXXX)
 chmod 0600 "$cookiejar" "$netrc"
 function finish {
   rm -rf "$cookiejar" "$netrc"
-    <% if @first_link.start_with? 'ftp' %>
+  <% if @first_link.start_with? 'ftp' %>
   <% # For FTP retrievals, we also need to clean up ~/.netrc file for safety reasons %>
       dot_netrc_tmp=$(mktemp ~/.netrc.tmp.XXXXXXXXXX)
   chmod 0600 "$dot_netrc_tmp"
   awk '!/<%= @first_link[/ftp:\/\/([^\/]*)\/.*/, 1].gsub('.', '\.') %>/' ~/.netrc > $dot_netrc_tmp && mv $dot_netrc_tmp ~/.netrc
   <% end %>
-    }
+}
 
 trap finish EXIT
 WGETRC="$wgetrc"
@@ -98,13 +98,17 @@ prompt_credentials
 
     fetch_urls() {
     if command -v curl >/dev/null 2>&1; then
+    <% unless @first_link.empty? %>
         setup_auth_curl
+    <% end %>
         while read -r line; do
     <% if @first_link.start_with? 'ftp' %>
-            curl -f -Og --netrc-file "$netrc" $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
-            <% else %>
-            curl -f -b "$cookiejar" -c "$cookiejar" -L -n -Og -- $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
-            <% end %>
+        curl -f -Og --netrc-file "$netrc" $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
+    <% elsif !@first_link.empty?%>
+        curl -f -b "$cookiejar" -c "$cookiejar" -L -n -Og -- $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
+    <% else %>
+        echo "No downloadable links are found."
+    <% end %>
     done;
     elif command -v wget >/dev/null 2>&1; then
         # We can't use wget to poke provider server to get info whether or not URS was integrated without download at least one of the files.
@@ -167,17 +171,25 @@ fetch_urls <<'EDSCEOF'
     }
 
     function onLoad() {
-      var doc = JSON.parse(this.response);
-      cmrHits = doc['CMR-Hits'];
-      document.getElementById('loading').innerHTML = 'Loading more... (parsed ' + (currentPage * 2000 > cmrHits ? cmrHits : (currentPage * 2000))+ ' of ' + cmrHits + ')';
-      var links = doc.links;
-      preContent = document.getElementById('script');
-      preContent.innerHTML += links.join("\n");
-      var next = getNextPageUrl();
-      if (next) {
-        fetchLinks(next);
+      if(this.status == 200) {
+        var doc = JSON.parse(this.response);
+        cmrHits = doc['CMR-Hits'];
+        document.getElementById('loading').innerHTML = 'Loading more... (parsed ' + (currentPage * 2000 > cmrHits ? cmrHits : (currentPage * 2000)) + ' of ' + cmrHits + ')';
+        var links = doc.links;
+        preContent = document.getElementById('script');
+        preContent.innerHTML += links.join("\n");
+        var next = getNextPageUrl();
+        if (next) {
+          fetchLinks(next);
+        }
+        else {
+          finish();
+        }
       }
       else {
+        document.getElementById('download-description').innerHTML = "Error retrieving download links from backend API. Request <div class='pre-container'><pre>" + this.responseURL
+            + "</pre></div> returns an error: <div class='pre-container'><pre>" + this.responseText + "</pre></div>";
+        document.getElementById('download-description').style.display = 'inline';
         finish();
       }
     }
