EDSC-1847: Renames OPeNDAP files when downloaded to avoid Apple filesystem woes

diff --git a/app/views/granules/prepare_opendap_script.html.erb b/app/views/granules/prepare_opendap_script.html.erb
--- a/app/views/granules/prepare_opendap_script.html.erb
+++ b/app/views/granules/prepare_opendap_script.html.erb
@@ -81,7 +81,7 @@ prompt_credentials() {
     read -p "Username (<%= @user %>): " username
     username=${username:-<%= @user %>}
     read -s -p "Password: " password
-    echo "machine urs.earthdata.nasa.gov login $username password $password" >> $netrc
+    echo "machine <%= @urs_root %> login $username password $password" >> $netrc
     <% if @first_link && @first_link.start_with?('ftp') %>
     echo "machine <%= @first_link[/ftp:\/\/([^\/]*)\/.*/, 1] %> login $username password $password" >> $netrc
     <% end %>
@@ -109,12 +109,18 @@ prompt_credentials
     if command -v curl >/dev/null 2>&1; then
         setup_auth_curl
         while read -r line; do
+          # Get everything after the last '/'
+          filename="${line##*/}"
+
+          # Strip everything after '?'
+          stripped_query_params="${filename%%\?*}"
+
         <% if @first_link && @first_link.start_with?('ftp') %>
-            curl -f -Og --netrc-file "$netrc" $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
+          curl -f -g --netrc-file "$netrc" -o $stripped_query_params $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
         <% elsif @first_link && !@first_link.empty? %>
-            curl -f -b "$cookiejar" -c "$cookiejar" -L --netrc-file "$netrc" -Og -- $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
+          curl -f -b "$cookiejar" -c "$cookiejar" -L --netrc-file "$netrc" -g -o $stripped_query_params -- $line && echo || exit_with_error "Command failed with error. Please retrieve the data manually."
         <% else %>
-            echo "No downloadable links are found."
+          echo "No downloadable links are found."
         <% end %>
         done;
     elif command -v wget >/dev/null 2>&1; then
